<?php
/**
 * Plugin Loader
 *
 * @package ChoctawNation
 * @subpackage HealthDashboard
 */

namespace ChoctawNation\HealthDashboard;

use ChoctawNation\HealthDashboard\WP\AdminScreen\Admin_Screen;
use ChoctawNation\HealthDashboard\Http\Rest_Router;
use ChoctawNation\HealthDashboard\WP\Notifier;
use ChoctawNation\HealthDashboard\WP\Plugin_Settings;

/** Inits the Plugin */
class Plugin_Loader {
	/**
	 * Plugin Settings
	 *
	 * @var Plugin_Settings $settings
	 */
	private Plugin_Settings $settings;

	/**
	 * Directory path of the plugin, used for loading assets and block metadata.
	 *
	 * @var string $dir_path
	 */
	private string $dir_path;

	/**
	 * Constructor
	 *
	 * @param string $dir_path The directory path of the plugin, used for loading assets and block metadata.
	 */
	public function __construct( string $dir_path ) {
		$this->settings = new Plugin_Settings();
		$this->dir_path = $dir_path;
	}

	/**
	 * Initializes the Plugin
	 *
	 * @return void
	 */
	public function activate(): void {
		$this->settings->initialize_defaults();
		flush_rewrite_rules();
	}

	/**
	 * Handles Plugin Deactivation
	 * (this is a callback function for the `register_deactivation_hook` function)
	 *
	 * @return void
	 */
	public function deactivate(): void {
		flush_rewrite_rules();
	}

	/**
	 * Handles Plugin Uninstallation
	 * (this is a callback function for the `register_uninstall_hook` function)
	 */
	public static function uninstall(): void {
		$settings = new Plugin_Settings();
		$settings->delete_settings();
	}

	/**
	 * Loads the Plugin
	 */
	public function load_plugin(): void {
		$notifier = new Notifier( array( 'kroelke@choctawnation.com', 'bperkins@choctawnation.com' ) );
		// load rest routers
		$rest_router = new Rest_Router( $this->settings, $notifier );
		add_action( 'rest_api_init', array( $rest_router, 'register_routes' ) );
		$settings_rest_controller = new WP\AdminScreen\Settings_Rest_Controller( $this->settings );
		add_action( 'rest_api_init', array( $settings_rest_controller, 'register_routes' ) );
		// load admin screen
		$admin_screen = new Admin_Screen( $this->settings );
		add_action( 'admin_menu', array( $admin_screen, 'register_menus' ) );
		add_action( 'admin_enqueue_scripts', array( $admin_screen, 'load_required_assets' ) );

		// load block
		add_action( 'init', array( $this, 'register_blocks' ) );
	}

	/**
	 * Registers the block(s) in the plugin's `build` directory using the metadata from the `blocks-manifest.php` file generated by the build process.
	 */
	public function register_blocks() {
		$blocks_path = $this->dir_path;
		/**
		 * Registers the block(s) metadata from the block.json files.
		 * Added in WordPress 6.8 to simplify the block metadata registration process added in WordPress 6.7.
		 *
		 * @see https://make.wordpress.org/core/2025/03/13/more-efficient-block-type-registration-in-6-8/
		 */
		if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
			wp_register_block_types_from_metadata_collection( $blocks_path . '/build/blocks', $blocks_path . '/build/blocks-manifest.php' );
		}

		/**
		 * Registers the block(s) metadata from block.json files.
		 * Added to WordPress 6.7 to improve the performance of block type registration.
		 *
		 * @see https://make.wordpress.org/core/2024/10/17/new-block-type-registration-apis-to-improve-performance-in-wordpress-6-7/
		 */
		if ( function_exists( 'wp_register_block_metadata_collection' ) ) {
			wp_register_block_metadata_collection( $blocks_path . '/build/blocks', $blocks_path . '/build/blocks-manifest.php' );
			return;
		}
		foreach ( include $blocks_path . '/build/blocks-manifest.php' as $block_name => $block_metadata ) {
			/**
			 * Registers the block type(s) manually for older WordPress versions.
			 *
			 * @see https://developer.wordpress.org/reference/functions/register_block_type/
			 */
			register_block_type( $blocks_path . '/build/blocks/' . $block_name, $block_metadata );
		}
	}
}